### ISSUE TITLE
python-tradingview-ta  retrieving multiple analysis error

### ISSUE THREAD

**Issue by mustafaerdogan90** [brian-the-dev/python-tradingview-ta#104]
input:
from tradingview_ta import *
analysis = get_multiple_analysis(screener="crypto", interval=Interval.INTERVAL_1_HOUR, symbols=["BINANCE:BTCUSDT", "BINANCE:ETHUSDT"])
print(analysis)

output
{'BINANCE:BTCUSDT': <tradingview_ta.main.Analysis object at 0x000002E3A83FB8B0>, 'BINANCE:ETHUSDT': <tradingview_ta.main.Analysis object at 0x000002E3A83FB8B0>}

What I want to do is just attract the opening closing high low daily candle prices of the coins.

**Comment by brian-the-dev** [comment]
Hello,

It seems that the library is working as intended. As you're using the `get_multiple_analysis` function and not the `get_analysis`, python-tradingview-ta returns a dict containing the symbols as the keys and an instance of `Analysis` as the value. If you're looking for the open/close/high/low price, you can access it via `print(analysis["BINANCE:BTCUSDT"].indicators["open"])` as per documentation. (You can replace `open` with `close`, `high`, or `low`) 

If you're looking for the daily price, do not use the 1-hour interval, use the 1-day interval instead. You can familiarize yourself with how the library works by reading the documentation available here: https://python-tradingview-ta.readthedocs.io/en/latest/usage.html. 

Hope this helps and good luck with your project!

**Comment by mustafaerdogan90** [comment]
> Merhaba,
> 
> Kütüphane istendiği gibi çalışıyor gibi görünüyor. `get_multiple_analysis`python-tradingview-ta işlevini değil de işlevi kullandığınız için `get_analysis`, python-tradingview-ta, sembolleri anahtar `Analysis`olarak ve değer olarak bir örneğini içeren bir dikte döndürür. Aç/kapa/yüksek/düşük fiyat arıyorsanız, `print(analysis["BINANCE:BTCUSDT"].indicators["open"])`belgelere göre erişebilirsiniz. ( , , veya `open`ile değiştirebilirsiniz )`close``high``low`
> 
> Günlük fiyat arıyorsanız 1 saatlik aralığı kullanmayın, bunun yerine 1 günlük aralığı kullanın. Burada bulunan belgeleri okuyarak kütüphanenin nasıl çalıştığını öğrenebilirsiniz: https://python-tradingview-ta.readthedocs.io/en/latest/usage.html .
> 
> Umarım bu yardımcı olur ve projenizde iyi şanslar!

The "get_multiple_analysis" I need is not working. I need OHLC data for this many symbols. Pulling data one by one, it takes too long.

I already know how to use the code below.
 TAH= TA_Handler(symbol=cid[1] + "PERP", screener="crypto", exchange="BINANCE", interval="1d")
TAH_indicators = UTAH.get_analysis().indicators

**Comment by mustafaerdogan90** [comment]
> What do you mean by 'not working'? Could you send me a screenshot of the error or a concise description of it?

![hata](https://user-images.githubusercontent.com/111326464/184920155-9f8a0937-64f3-4e5a-bd6f-935743886700.png)
from tradingview_ta import *
analysis = get_multiple_analysis(screener="crypto", interval=Interval.INTERVAL_1_HOUR, symbols=["BINANCE:BTCUSDT", "BINANCE:ETHUSDT"])
print(analysis)

**Comment by brian-the-dev** [comment]
As I previously stated, there is nothing wrong with the library. It's working as intended and there is no exception/runtime error. Please re-read my previous comment (https://github.com/brian-the-dev/python-tradingview-ta/issues/104#issuecomment-1216789035) and replace the `print(analysis)` with the one I wrote there.

**Comment by mustafaerdogan90** [comment]
> print(analysis["BINANCE:BTCUSDT"].indicators["open"])

YOU'RE DOING GREAT, THANK YOU.
