### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by jsgaston** [brian-the-dev/python-tradingview-ta#116]
**Describe the bug**
Hi, my trading bot doesnt work. The problem seems to be this:

IndexError: single positional indexer is out-of-bounds

from here:

    df['Date'] = pd.to_datetime(df['Date'], format = date_change)

# Create a variable that is the date column
    Dates = df['Date']

    from ta import add_all_ta_features # Library that does financial technical analysis 

    df = add_all_ta_features(df, "Open", "High", "Low", "Close", "Volume", fillna=True, vectorized=True) 

(or is it not)?

**Version**
python 3.7.9
win 11
tradingview-ta 3.3.0 

or is it not this?

**Comment by brian-the-dev** [comment]
Hi!

I believe you're not in the correct repo. My library (tradingview-ta) does not have a function `called add_all_ta_features`. You're probably looking for https://github.com/bukosabino/ta/. I'm closing this issue, have a good one!
