### ISSUE TITLE
"RECOMMENDATION": recommend_summary

### ISSUE THREAD

**Issue by waudinio27** [brian-the-dev/python-tradingview-ta#31]
1) Can you tell me how to transform the "RECOMMENDATION": recommend_summary - value into an if statement for the automation of the analysis.summary to create order statements? 

     So that if 'RECOMMENDATION': 'BUY'  - I can create a buy order at my Broker with it .... 

2) How to store the "RECOMMENDATION": recommend_summary - value in a Pandas dataframe for using it later? And is it possible to make the analysis for two assets and put them into one Pandas dataframe for the construction of a portfolio?

Thank you for your answer - your help is appreciated a lot

**Comment by deathlyface** [comment]
Hello @waudinio27,

1. If-else for "RECOMMENDATION"

```python
from tradingview_ta import TA_Handler, Interval, Exchange

handler = TA_Handler(
    symbol="TSLA",
    screener="america",
    exchange="NASDAQ",
    interval=Interval.INTERVAL_1_DAY
)
analysis = handler.get_analysis()

if analysis.summary["RECOMMENDATION"] == "BUY":
   # Buy
elif analysis.summary["RECOMMENDATION"] == "SELL":
   # Sell
else:
   # Neutral
```
You can read your broker's API to create your order. However, I don't recommend you to use python-tradingview-ta to trade automatically.

2. Pandas DataFrame

You can loop the `get_analysis()` and append a dictionary containing time and recommendation to a list.
```python
import pandas as pd
import time
from tradingview_ta import TA_Handler, Interval, Exchange

data_list = []

handler = TA_Handler(
    symbol="TSLA",
    screener="america",
    exchange="NASDAQ",
    interval=Interval.INTERVAL_1_MINUTE
)

for x in range(5): #repeat 5 times (change it to whatever you want)
    recommendation = handler.get_analysis().summary["RECOMMENDATION"] # Get recommendation
    time_in_ms = int(round(time.time() * 1000)) # Get time in millisecond
    data_list.append({"time (ms)": time_in_ms, "recommendation": recommendation})
    time.sleep(60) # Wait 1 minute before calling get_analysis() again (change it to whatever you want)

pd_dataframe = pd.DataFrame.from_dict(data_list) # create pd dataframe from dictionary
print(pd_dataframe)
#        time (ms) recommendation
# 0  1613260245060            BUY
# 1  1613260305974            BUY
# ...
# ...
```
Yes, it is possible to add multiple assets into a dataframe. You can create another instance of `TA_Handler`, call get_analysis on both assets, and replace the append code.
```python
...
recommendation1 = handler1.get_analysis().summary["RECOMMENDATION"] # recommendation for asset1
recommendation2 = handler2.get_analysis().summary["RECOMMENDATION"] # recommendation for asset2
time_in_ms = int(round(time.time() * 1000)) # Get time in millisecond
data_list.append({"time (ms)": time_in_ms, "asset1": "first asset", "recommendation1": recommendation1 "asset2": "second asset", "recommendation2": recommendation2})
...
```
```python
pd_dataframe = pd.DataFrame.from_dict(data_list) # create pd dataframe from dictionary
print(pd_dataframe)
#        time (ms)              asset1 recommendation1              asset2 recommendation2
# 0  1613260245060      NAME OF ASSET1             BUY      NAME OF ASSET2            SELL
# 1  1613260305974      NAME OF ASSET1            SELL      NAME OF ASSET2             BUY
# ...
# ...
```

Hope this answers your questions. Let me know if you have another question.

**Comment by waudinio27** [comment]
Hello and thank you so much for your fast and precise reply! This is really helping me in answering my questions!

I have one more thing on my mind. I was wondering why you don't recommend the python-tradingview-ta to trade automatically? Is there a special reason?

I want to try it with the demo account to see how it is working out.

**Comment by deathlyface** [comment]
Tradingview sometimes change their algorithm, like in [v3.2.1](https://github.com/deathlyface/python-tradingview-ta/releases/tag/v3.2.1). It's best to try paper trading first.

**Comment by waudinio27** [comment]
I have implemented everything like you recommended so far, but I need your expert advise one more time.

How is it possible to make a Multi Time Frame - MTF script?

I want to make a loop that does the analysis for 5  minutes, 15 minutes and one hour.
Only when all of them are positive I want to enter a trade and stay with one open position until the signal changes ....

Thanks a lot I really appreciate your help!

**Comment by deathlyface** [comment]
You can set a variable containing the last order (buy/sell). It's safe to call all three `get_analysis()`  every 5 minutes. Here is the pseudocode:
```
last_order = ""

while True:
    # if last order is sell or empty, and all recommendation is buy, then buy
    if last_order == "" or last_order == "sell":
        if 5min.get_analysis().summary["RECOMMENDATION"] in ["BUY", "STRONG_BUY"] and 15min.get_analysis().summary["RECOMMENDATION"] in ["BUY", "STRONG_BUY"] and 1hour.get_analysis().summary["RECOMMENDATION"] in ["BUY", "STRONG_BUY"]:
            create_buy_order()
            last_order = "buy"

    # if last order is buy, and all recommendation is sell, then sell
    if last_order == "buy":
        if 5min.get_analysis().summary["RECOMMENDATION"] in ["SELL", "STRONG_SELL"] and 15min.get_analysis().summary["RECOMMENDATION"] in ["SELL", "STRONG_SELL"] and 1hour.get_analysis().summary["RECOMMENDATION"] in ["SELL", "STRONG_SELL"]:
            create_sell_order()
            last_order = "sell"

    # repeat every 5 minutes (300 seconds)
    time.sleep(300)
```

**Comment by waudinio27** [comment]
You are the Best! I will try to get it running like this during the week :-)
