### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by DidierRLopes** [brian-the-dev/python-tradingview-ta#39]
I'm getting this:
```
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

when doing:
```
stock_recommendation = TA_Handler(
                  symbol=ticker,
                  screener=screener,
                  exchange=exchange,
                  interval=interv,
              )
              d_recommendation = stock_recommendation.get_analysis().summary
```
with ticker as `PLTR`. It works for others

**Comment by deathlyface** [comment]
Hi @DidierRLopes,
I would like to help you, but can you please be more specific? What is the value of `screener`, `exchange`, and `interv`? What are you trying to compare using `>=`?

**Comment by DidierRLopes** [comment]
Hey @deathlyface,

Thank you. Yes. So I'm using:
```
PLTR
america
NYSE
1M
```

I'm not doing any comparison, that error comes from:
```
stock_recommendation.get_analysis().summary
```

**Comment by deathlyface** [comment]
Oh, my bad. I'll look it up.

**Comment by deathlyface** [comment]
I think I found the problem. It's not from the `tradingview-ta`, but from the TradingView. If you open https://tradingview.com/symbols/NYSE-PLTR/technicals/ and move to the 1-month tab, the value is all zero.

![Screenshot from 2021-04-24 06-53-51](https://user-images.githubusercontent.com/40331046/115939904-f1614e80-a4c9-11eb-804e-bb2fd134894d.png)

Unfortunately, there's nothing I can do. You can switch to another interval such as `"1W"` (1-week), or try contacting TradingView support.

**Comment by DidierRLopes** [comment]
Thank you for digging!!

Could you output a more comprehensible error or so?

**Comment by deathlyface** [comment]
I'll release the next version with a clear error message.

**Comment by DidierRLopes** [comment]
Thank you for this!!

**Comment by CuongITL** [comment]
Quick fixed:  modified 'main.py' from site-packages\tradingview_ta:
IN line 80: def calculate(indicators, screener, symbol, exchange, interval):
Replace line 85,86,87 with code:

```
    recommend_oscillators = "NEUTRAL"
    recommend_summary = "NEUTRAL"
    recommend_moving_averages = "NEUTRAL"
    if indicators[0] is not None:
        recommend_oscillators = Compute.Recommend(indicators[0])
    if indicators[1] is not None:
        recommend_summary = Compute.Recommend(indicators[1])
    if indicators[2] is not None:
        recommend_moving_averages = Compute.Recommend(indicators[2])
```

Good luck.
