### ISSUE TITLE
Recommendations are not accurate

### ISSUE THREAD

**Issue by dcaspi** [brian-the-dev/python-tradingview-ta#45]
I've noticed at times that the recommendation tags returned from the library don't match the ones on TV (I'm referring to the NEUTRAL, BUY, etc.. tags).

After comparing the code, it seems like `Compute.Recommend()` should indeed be adjusted.

Compare the following:

```
def Recommend(value):
        """Compute Recommend

        Args:
            value (float): recommend value

        Returns:
            string: "STRONG_BUY", "BUY", "NEUTRAL", "SELL", "STRONG_SELL", or "ERROR"
        """
        if (value >= -1 and value < -.5):
            return Recommendation.strong_sell
        elif (value >= -.5 and value < 0):
            return Recommendation.sell
        elif (value == 0):
            return Recommendation.neutral
        elif (value > 0 and value <= .5):
            return Recommendation.buy
        elif (value > .5 and value <= 1):
            return Recommendation.strong_buy
        else:
            return Recommendation.error
```

to the relevant code on TV:
```
computeRecommendSignal: e=>{
                let t;
                return e >= -1 && e < -.5 && (t = n.STRONG_SELL),
                e >= -.5 && e < -.1 && (t = n.SELL),
                e >= -.1 && e <= .1 && (t = n.NEUTRAL),
                e > .1 && e <= .5 && (t = n.BUY),
                e > .5 && e <= 1 && (t = n.STRONG_BUY),
                t
}
```

**Comment by brian-the-dev** [comment]
Hello @dcaspi,

Thanks for informing me. I checked and they also changed the ComputeAOSignal algorithm. I'm working on it and will release a fix as soon as possible.

**Comment by brian-the-dev** [comment]
This bug has been fixed. Please update to [v3.2.4](https://pypi.org/project/tradingview-ta/3.2.4/) using  `pip install -U tradingview_ta`. You may close this issue if you don't have any other problems.

Once again, thanks for informing me. Have a good one!

**Comment by dcaspi** [comment]
Thanks for the quick fix!
