### ISSUE TITLE
Getting Error: Can't access TradingView's API 

### ISSUE THREAD

**Issue by NightMasterX** [brian-the-dev/python-tradingview-ta#50]
Error:
-> Exception: Can't access TradingView's API. HTTP status code: 400. Check for invalid symbol, exchange, or indicators.

Error Code: https://sourceb.in/3u8p7jc5Zp
Code without Indicators (it works too): https://srcb.in/IB3ynySOAw

I am Getting this error when I try to use indicators. This does not happen when I do not use Indicators. 

Screenshot:
https://user-images.githubusercontent.com/65802925/124942806-94395b80-e029-11eb-8079-655bdb5f6a4c.png

**Version**
 - OS: Windows 10 Pro
 - Python: 3.9.6 64Bit
 - TradingView-TA: [3.2.5]

**Comment by brian-the-dev** [comment]
I think you made a typo. Try `"VWMA"` instead of `"VMWA"`.

**Comment by NightMasterX** [comment]
Can't believe this was the Problem, thanks tho.
