### ISSUE TITLE
AttributeError: partially initialized module 'tradingview_ta' has no attribute 'TA_Handler' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ThomasHoutrique** [brian-the-dev/python-tradingview-ta#53]
**Describe the bug**
when i try to run the exemple code i get this error : AttributeError: partially initialized module 'tradingview_ta' has no attribute 'TA_Handler' (most likely due to a circular import)

**To Reproduce**
Steps to reproduce the behavior.
run the exemple code

**Expected behavior**
Something working ig ?

**Code/Screenshots**
If applicable, attach your code or add screenshots to help explain your problem.
```
import tradingview_ta

tesla = tradingview_ta.TA_Handler(
    symbol="TSLA",
    screener="america",
    exchange="NASDAQ",
    interval=tradingview_ta.Interval.INTERVAL_1_DAY
)
print(tesla.get_analysis().summary)
# Example output: {"RECOMMENDATION": "BUY", "BUY": 8, "NEUTRAL": 6, "SELL": 3}
```

**Version**
 - OS: Ubuntu 21.04, Windows 10 Both tested
 - Python: 3.9.6
 - TradingView-TA: latest from pip
Thanks 😉

**Comment by brian-the-dev** [comment]
Hi @ThomasHoutrique,

I am unable to reproduce this issue. The code works perfectly fine on my Pop!_OS 21.04 (Python 3.9.5), Ubuntu 20.04 (Python 3.8.10), and Docker (Python 3.9.6).

![image](https://user-images.githubusercontent.com/40331046/125372426-45831d00-e3ad-11eb-8274-76aca62571b2.png)

![image](https://user-images.githubusercontent.com/40331046/125372346-1b315f80-e3ad-11eb-8a14-adb6a80ea1ef.png)

![image](https://user-images.githubusercontent.com/40331046/125372682-e540ab00-e3ad-11eb-85c0-e4c7109ff976.png)

Can you try importing `tradingview_ta` in a different way? Try this code and let me know the result.

```python
from tradingview_ta import TA_Handler, Interval

tesla = TA_Handler(
    symbol="TSLA",
    screener="america",
    exchange="NASDAQ",
    interval=Interval.INTERVAL_1_DAY
)
print(tesla.get_analysis().summary)
```

**Comment by ThomasHoutrique** [comment]
Hey, kinda strange but it's working perfectly on my raspberry pi.
Thanks for your help 👍
