### ISSUE TITLE
How exactly is RSI calculated?

### ISSUE THREAD

**Issue by zabop** [brian-the-dev/python-tradingview-ta#60]
First of all, very cool package. Congratulations!

I have a quesion about RSI indicator. I do:

```
import tradingview_ta

handler = tradingview_ta.TA_Handler(
    symbol="XMRBUSD",
    exchange="binance",
    screener="crypto",
    interval="1m",
    timeout=None
)

analysis = handler.get_analysis()

print(analysis.indicators["RSI"])
```

I get: `39.68717964`

However, at a time instant very similar to this (ie as fast as I can take a screenshot after running the above Python script, ie a few sec max), Binance looks like this:

![image](https://user-images.githubusercontent.com/20886570/129924476-79b5f996-7d3f-4ebf-b990-e25fd73e371e.png)

As you can see, the two RSI values do not match. Would it be possible to know the exact details of the RSI indicator returned by `handler.get_analysis()`? Maybe the discrepancy arises because different lengths are used. I could check this by adjusting the length on Binance:

![image](https://user-images.githubusercontent.com/20886570/129924775-c1bb937b-1797-4f56-8714-8f462af1ff4b.png)

But to do this, I would need to know what length the RSI uses here.

Thank you!

**Comment by brian-the-dev** [comment]
Hi @zabop,

TradingView-TA does not do any calculation on RSI. The data is the same as provided by TradingView. Compare [the website](https://www.tradingview.com/symbols/XMRBUSD/technicals/) with the Python output:
![image](https://user-images.githubusercontent.com/40331046/130160699-a2b30ad0-c9d9-48e3-8d3b-84c2484887f8.png)
![image](https://user-images.githubusercontent.com/40331046/130161038-a72091c7-9eb3-4472-bf97-535c8ba4164e.png)
If you look at the text next to RSI, I think they use a length of 14. Also notice that the RSI is the same, except TradingView rounded it to 2 decimal places.

One of the reasons is that the data might be delayed. TradingView retrieves it from Binance, then TradingView-TA retrieves it from TradingView. You can try retrieving the data from Binance directly using [python-binance](https://github.com/sammchardy/python-binance).

I hope this helps. If you still have questions, you can reply to this comment.

**Comment by zabop** [comment]
Thank you for the detailed answer, it is very helpful! I don't have more questions.
