### ISSUE TITLE
add_indicators

### ISSUE THREAD

**Issue by anakein** [brian-the-dev/python-tradingview-ta#62]
Last Tradingview_ta version

analysis = handler[pair].get_analysis()
analysis.add_indicators(["average_volume_30d_calc","average_volume_60d_calc"])

'Analysis' object has no attribute 'add_indicators'

**Comment by brian-the-dev** [comment]
Hi @anakein,

Use the `add_indicators()` function on the handler, not the analysis. Here's an example:

```python
from tradingview_ta import TA_Handler, Interval

btcusdt = TA_Handler(
  symbol="BTCUSDT",
  exchange="binance",
  screener="crypto",
  interval=Interval.INTERVAL_1_DAY
)

btcusdt.add_indicators(["average_volume_30d_calc","average_volume_60d_calc"])

analysis = btcusdt.get_analysis()
```

**Comment by martinbouhier** [comment]
Is there any way to add an indicator who is not in the https://pastebin.com/1DjWv2Hd??

**Comment by brian-the-dev** [comment]
> Is there any way to add an indicator who is not in the https://pastebin.com/1DjWv2Hd??

No, unless you know the exact algorithm used, you can't add those indicators.
