### ISSUE TITLE
KeyError: 'EMA200'

### ISSUE THREAD

**Issue by anakein** [brian-the-dev/python-tradingview-ta#63]
**Version**
 - OS: all
 - Python:  3.9.1
 - TradingView-TA:  3.2.8
never crash pp but dotay show me this:

    if analysis.moving_averages ['COMPUTE'][indicator] == 'BUY': maCheck +=1
KeyError: 'EMA200'
SMA200 launch same error

**Comment by brian-the-dev** [comment]
Hi @anakein,

Some symbols do not have EMA200/SMA200, especially with new cryptocurrency or stock that has less than 200 days history. Do you mind sharing the symbol that causes this error? 

Example:

![image](https://user-images.githubusercontent.com/40331046/131619279-25b02769-f830-4a6d-9432-ca2f54e681ac.png)

To prevent this error, you can check if `indicator` is in the dict. Example:
```python
if indicator in analysis.moving_averages['COMPUTE']:
    if analysis.moving_averages['COMPUTE'][indicator] == "BUY":
        maCheck += 1
else:
    # Do something
```

PS: Next time, please use the issue template correctly (give a **detailed** description about your issue, share the symbol/exchange, or attach a screenshot), thanks.

**Comment by anakein** [comment]
sorry again, but It is an intermittent problem, it also happens to me with some signals, 1 of 20 times, an exception jumps

In indicators added too
File "/home/pi/BeastBot/Strategy1.py", line 260, in analyze
    str(analysis.indicators["Candle.3WhiteSoldiers"])+
AttributeError: 'dict' object has no attribute 'indicators'
it last is first time, my testbot is working 2 days and load each 15 minutes tradingview_ta datas

**Comment by brian-the-dev** [comment]
Your error seems strange to me. It means that `analysis` is a dictionary, while it should be an instance of the `Analysis` class. Make sure that you didn't assign anything to `analysis` other than from `get_analysis()`. Do you mind sharing your code so I can look into it?

**Comment by anakein** [comment]
sure. Is very strange, today Zero problem. At last night sometimes error in Candle.TriStar.Bullish others in Candle.3WhiteSoldiers.
only 3 last indicators:
             Candle.3WhiteSoldiers",
            "Candle.TriStar.Bearish",
            "Candle.TriStar.Bullish


  for pair in markettickers:
        handler[pair] = TA_Handler(
            symbol=pair,
            exchange=EXCHANGE,
            screener=SCREENER,
            interval=INTERVAL,
            timeout= 10)

        handler[pair].add_indicators(["ATR",
            "Candle.AbandonedBaby.Bearish",
            "Candle.AbandonedBaby.Bullish",
            "Candle.Engulfing.Bearish",
            "Candle.Harami.Bearish",
            "Candle.Engulfing.Bullish",
            "Candle.Harami.Bullish",
            "Candle.Doji",
            "Candle.Doji.Dragonfly",
            "Candle.EveningStar",
            "Candle.Doji.Gravestone",
            "Candle.Hammer",
            "Candle.HangingMan",
            "Candle.InvertedHammer",
            "Candle.Kicking.Bearish",
            "Candle.Kicking.Bullish",
            "Candle.LongShadow.Lower",
            "Candle.LongShadow.Upper",
            "Candle.Marubozu.Black",
            "Candle.Marubozu.White",
            "Candle.MorningStar",
            "Candle.ShootingStar",
            "Candle.SpinningTop.Black",
            "Candle.SpinningTop.White",
            "Candle.3BlackCrows",
            "Candle.3WhiteSoldiers",
            "Candle.TriStar.Bearish",
            "Candle.TriStar.Bullish"])

 for pair in markettickers:
        try:
            analysis = handler[pair].get_analysis()
        except Exception as e:
            print("Strategy:")
            print("Exception:")
            print(e)
            print (f'Coin: {pair}')
            print (f'handler: {handler[pair]}')
        
        print (f'Coin: {pair}  Strategy Config:  TP: {s_tp} SL: {s_sl} With TrailStoploss: {s_utsl} {s_ttp} {s_tsl}')
        atr_result = False
        Volume_Result = False 


        candle = (
            str(analysis.indicators["Candle.Kicking.Bearish"])+
            str(analysis.indicators["Candle.AbandonedBaby.Bearish"])+
            str(analysis.indicators["Candle.AbandonedBaby.Bullish"])+
            str(analysis.indicators["Candle.Engulfing.Bearish"])+
            str(analysis.indicators["Candle.Harami.Bearish"])+
            str(analysis.indicators["Candle.Engulfing.Bullish"])+
            str(analysis.indicators["Candle.Harami.Bullish"])+
            str(analysis.indicators["Candle.Doji"])+
            str(analysis.indicators["Candle.Doji.Dragonfly"])+
            str(analysis.indicators["Candle.EveningStar"])+
            str(analysis.indicators["Candle.Doji.Gravestone"])+
            str(analysis.indicators["Candle.Hammer"])+
            str(analysis.indicators["Candle.HangingMan"])+
            str(analysis.indicators["Candle.InvertedHammer"])+
            str(analysis.indicators["Candle.Kicking.Bearish"])+
            str(analysis.indicators["Candle.Kicking.Bullish"])+
            str(analysis.indicators["Candle.LongShadow.Lower"])+
            str(analysis.indicators["Candle.LongShadow.Upper"])+
            str(analysis.indicators["Candle.Marubozu.Black"])+
            str(analysis.indicators["Candle.Marubozu.White"])+
            str(analysis.indicators["Candle.MorningStar"])+
            str(analysis.indicators["Candle.ShootingStar"])+
            str(analysis.indicators["Candle.SpinningTop.Black"])+
            str(analysis.indicators["Candle.SpinningTop.White"])+
            str(analysis.indicators["Candle.3BlackCrows"])+
            str(analysis.indicators["Candle.3WhiteSoldiers"])+
            str(analysis.indicators["Candle.TriStar.Bearish"])+
            str(analysis.indicators["Candle.TriStar.Bullish"]))

**Comment by brian-the-dev** [comment]
Your code seems fine to me, but it might be because an exception occurred while calling `get_analysis()`. When an exception occurs, your code will attempt to add the indicators, instead of skipping the pair. Try adding `continue` in the except, so when an error occurs, it will directly continue to the next pair.

```python
try:
    analysis = handler[pair].get_analysis()
except Exception as e:
    print("Strategy:")
    print("Exception:")
    print(e)
    print (f'Coin: {pair}')
    print (f'handler: {handler[pair]}')
    continue

# If an error occurs, the code in this part won't be run. Example:
print("Here!")
# "Here!" won't be printed, it will directly continue to the next pair in markettickers.


```

References: https://www.tutorialspoint.com/python/python_continue_statement.htm

I don't know if this will fix your error, but it's worth trying. Please keep me updated if you still receive the error.
