### ISSUE TITLE
Include new 30 minutes and 2 hours interval to the existing interval list

### ISSUE THREAD

**Issue by phoneywc** [brian-the-dev/python-tradingview-ta#64]
Hello Brian,

Is is possible to add the 2 new time intervals to the existing list?
-30 minutes
-2 hours

Proof:
![image](https://user-images.githubusercontent.com/35164561/131608190-d2db55a3-ecfe-4ca0-b18a-6ecaa35e688a.png)

**Comment by brian-the-dev** [comment]
Hi @phoneywc,

Thanks for informing me, never saw it before. Yes, this is highly possible and I'll add them soon.

**Comment by brian-the-dev** [comment]
Added in v3.2.9, update your tradingview_ta using `pip install -U tradingview-ta`. 

New interval: `INTERVAL_30_MINUTES` and `INTERVAL_2_HOUR`

Code example:

```python
from tradingview_ta import TA_Handler, Interval

handler = TA_Handler(
    symbol="BTCUSDT",
    screener="crypto",
    interval=Interval.INTERVAL_2_HOUR,
    exchange="binance"
)

analysis = handler.get_analysis()
print(analysis.summary)
```

If you have any questions, please reply below. Otherwise, you may close this issue.

**Comment by phoneywc** [comment]
Hello Brian,

It's working as intended! Thanks and I will be resolving this enhancement request.
