### ISSUE TITLE
getting symbol XSUSHIUSDT

### ISSUE THREAD

**Issue by mostar** [brian-the-dev/python-tradingview-ta#66]
Hello,

I fail to retrieve symbol XSUSHIUSDT using
screener: CRYPTO  
exchange: SUSHISWAP

On my local installation and https://tradingview.brianthe.dev/
You can see it in tradingview

https://www.tradingview.com/symbols/XSUSHIUSDT/?exchange=SUSHISWAP

Is it something you should add to the code ?

**Comment by brian-the-dev** [comment]
Duplicate of [#28](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271) and #11.
