### ISSUE TITLE
Getting indexes data

### ISSUE THREAD

**Issue by sinaFa** [brian-the-dev/python-tradingview-ta#67]
Hello,
Currently you have several screeners 'binance', 'america', etc. I've checked the following page:
https://tvdb.brianthe.dev/

And it seems that the indexes are not included.
I'm interessted about the 'TOTAL' symbol which is an index computed by TradingView (the exchange is CRYPTOCAP with the TV icon).
Is there a way to get this?
I can maybe help if this needs modification of your library

**Comment by brian-the-dev** [comment]
HI @sinaFa,

Unfortunately, all indices don't have a technical analysis. This library will only work if there is a "Technicals" tab on the overview page (see [this](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271) for reference). There's nothing we can do, with or without modification. I'm closing this issue as it is currently unfixable.

**Comment by sinaFa** [comment]
I see,
Thanks for your answer!
