### ISSUE TITLE
Values not updating

### ISSUE THREAD

**Issue by sinaFa** [brian-the-dev/python-tradingview-ta#71]
Hello,
First, thanks for the great library!
I'm trying to retrieve data for the SPY (SPDR S&P 500 ETF TRUST) symbol using the following code:
`symbol = TA_Handler(
    symbol="SPY",
    screener="america",
    exchange="AMEX",
    interval=Interval.INTERVAL_5_MINUTES
)`

I receive some data but the problem is that data is never refreshed. 
I looked at your screener on 'https://tvdb.brianthe.dev/' and searching for SPY, it indicates the exchange as AMEX.
However, in TradingView website, the exchange for SPY is indicated as 'NYSE Arca'. Could this be an issue?
It also has a 'technical' page at:
https://www.tradingview.com/symbols/AMEX-SPY/technicals/

Thanks for your help

**Comment by brian-the-dev** [comment]
I just checked TradingView's website, `"AMEX"` is the correct exchange. You need to call `get_analysis()` every time you want to fetch new data. If you don't have any other questions, you may close this issue. Otherwise, please reply below.

![image](https://user-images.githubusercontent.com/40331046/134126453-ca0f3459-9b5f-4154-a7df-c50a87fe0378.png)

**Comment by sinaFa** [comment]
Thanks for the reply.
Yes but the problem is that the values are not refreshed. Of course, I call everytime get_analysis() but I always get the same values.
I don't have this problem with other symbols. 

Code used is the same as above, can you reproduce the issue?

**Comment by brian-the-dev** [comment]
![image](https://user-images.githubusercontent.com/40331046/134143897-561ff84d-830d-4d16-ad77-ece1fd9e60ec.png)
![image](https://user-images.githubusercontent.com/40331046/134144373-77b6753f-d152-4425-8310-ebb224c5faa9.png)

Yes, I can reproduce this issue. However, this has nothing to do with this library, as all analysis comes from their website. If you open their site and switch to the 5 minutes tab, you can see the values not updating too. Unfortunately, there's nothing I can do to fix this, you can try other intervals or try contacting TradingView.
