### ISSUE TITLE
Add ticker to the database

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [brian-the-dev/python-tradingview-ta#72]
Hi, can you help add OKEX: BABYDOGEUSDT to the database?
Thanks,
Daniel

**Comment by brian-the-dev** [comment]
Hi @Daniel-Trung-Nguyen,

Unfortunately, I am not affiliated with TradingView, so I don't have the access to their database. Technical analysis for BABYDOGEUSDT is not available at the moment (see #66 for a similar issue). Not all stock/crypto is supported by `tradingview-ta`, please check using https://tvdb.brianthe.dev.

I will close this issue as it's impossible to retrieve technical analysis from unsupported symbols.
