### ISSUE TITLE
Stoch.RSI.D indicator

### ISSUE THREAD

**Issue by rob3662** [brian-the-dev/python-tradingview-ta#73]
Is it possible to get the Stoch.RSI.D indicator added? I see that the Stoch.RSI.K indicator is available.

**Comment by brian-the-dev** [comment]
Hi @rob3662,

Sorry for the late response. Yes, it's possible, just use the `add_indicators()` function. Example:
```python
from tradingview_ta import *

handler = TA_Handler(
    screener="crypto",
    exchange="binance",
    symbol="BTCUSDT",
    interval=Interval.INTERVAL_1_HOUR
)

# Add the Stoch.RSI.D indicator
handler.add_indicators(["Stoch.RSI.D"])

# Retrieve indicators and get analysis
analysis = handler.get_analysis()

# Print Stoch.RSI.D
print(analysis.indicators["Stoch.RSI.D"])
```

I'm going to close this issue. If you still have difficulties, you can reply/reopen this issue. Have a good one.

**Comment by brian-the-dev** [comment]
Yes, you can use the workaround:
1. Put `from tradingview_ta import TradingView` at the start of your script.
2. Run `TradingView.indicators.append("Stoch.RSI.D")` **before** calling `get_multiple_analysis`.

**Comment by rob3662** [comment]
Great, thank you.
