### ISSUE TITLE
Index recommendation is not working .

### ISSUE THREAD

**Issue by ajit1310** [brian-the-dev/python-tradingview-ta#74]
**Is your feature request related to a problem? Please describe.**
at present it showing the recommendations only for stocks  and not Index .
**Describe the solution you'd like**
I know Tradingview is not showing Index technicals ,  can your script calculation the technical indicators( or get ready made from somewhere) and show the summary like stocks .

**Comment by brian-the-dev** [comment]
Hi, @ajit1310,

Unfortunately, this is currently impossible as not only they don't show the summary, but the indicators are also not available.

> can your script calculation the technical indicators

All indicators are already calculated locally (TradingView is just to get the indicators).

> or get ready made from somewhere

If the data (indicators) are not from TradingView, the name wouldn't be TradingView-TA. I recommend you to try `yfinance` and `pandas-ta`.

I'm going to close this issue as it is unfixable. Good luck with your project and have a nice day.
