### ISSUE TITLE
Unable to pull information from CL1!

### ISSUE THREAD

**Issue by phoneywc** [brian-the-dev/python-tradingview-ta#77]
Hi Brian,

I am unable to pull TA information from CL1!, however manually I am able to read all its TA data.

![image](https://user-images.githubusercontent.com/35164561/146143893-eeb2d489-bed3-4ae3-972b-745c0883ca8b.png)

![image](https://user-images.githubusercontent.com/35164561/146144139-90255d2f-466e-496d-a0cd-cbd7c13dee3d.png)

**Comment by brian-the-dev** [comment]
HI @phoneywc,

Try using `america` for the screener.

![image](https://user-images.githubusercontent.com/40331046/146146866-d055be38-bc5d-487f-b52c-f7390710788b.png)

I hope this helps. If you still have difficulties or questions, don't hesitate to reply/comment on this issue.

**Comment by phoneywc** [comment]
Thanks Brian!
Quick response and solution that totally works!
