### ISSUE TITLE
add new pair in crypto

### ISSUE THREAD

**Issue by hossain93** [brian-the-dev/python-tradingview-ta#82]
hi brian
can you add another pair coin. your lib is good but it is need to be strong with add another data

**Comment by brian-the-dev** [comment]
Hi @hossain93,

I do not control the availability of the data. All data is provided by TradingView. Anything available in TradingView (as long as it has a [technicals tab](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271)), should be available in tradingview-ta. 

I'm going to close this issue. If you still have questions feel free to reply. Have a good one.
