### ISSUE TITLE
BTC Dominance data

### ISSUE THREAD

**Issue by returnsomeday2** [brian-the-dev/python-tradingview-ta#84]
How to pull data for BTCD (BTC dominance) and total crypto cap (total)?

**Comment by brian-the-dev** [comment]
Hi @returnsomeday2,

You can't. Currently, tradingview-ta can only retrieve most stocks, CFD, crypto, and futures, not indices. Both BTC-D and TOTAL are categorized as indices, therefore they don't have the 'Technicals' tab. In order for tradingview-ta to work, there must be a 'Technicals' tab on TradingView's website: see [this example](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271).

I'm going to close this issue as it is a limitation from TradingView's side. If you still have questions feel free to reply. Have a nice day.
