### ISSUE TITLE
Problem with adding new indicator 

### ISSUE THREAD

**Issue by m100jek** [brian-the-dev/python-tradingview-ta#94]
Hey, 
I have hard time adding new indicator. I want to add RSI 8, by default it is RSI 14 and I don't know how or is this even possible.
if there is anyone willing to help i would appreciate

**Comment by brian-the-dev** [comment]
Hi @m100jek,

Only RSI14 and RSI7 are supported by the TradingView scanner API. At this time, there is no way to customize the RSI length. However, you can still use RSI7 as an alternative, which is the closest to RSI8. To add RSI7, call the `add_indicators()` function:

```python
from tradingview_ta import *

handler = TA_Handler(
    screener="crypto",
    interval= Interval.INTERVAL_1_HOUR,
    symbol="ETCUSDT",
    exchange="binance",
)

handler.add_indicators(["RSI7"])

analysis = handler.get_analysis()
print(analysis.indicators["RSI7"])
# Output: 44.93608397
```

**Comment by m100jek** [comment]
Thank you so much for the answer. U are awsome
