### ISSUE TITLE
Adding an indicator?

### ISSUE THREAD

**Issue by noahvogt1** [brian-the-dev/python-tradingview-ta#96]
I would like to add the Nadaraya Watson Envelope indicator, but I don't understand how I would go about doing it. If I could get help on this issue, that would be fantastic.

**Comment by brian-the-dev** [comment]
Unfortunately, user-created indicators are not supported. Tradingview-ta only supports built-in indicators. See the complete list [here](https://pastebin.com/1DjWv2Hd).
